import { execFileSync } from "node:child_process";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { changedFilesForRepo } from "../src/git-diff.js";
import { readTsconfigAliases } from "../src/extract.js";

const roots: string[] = [];

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

async function tempDir(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "keto-git-"));
  roots.push(root);
  return root;
}

function git(cwd: string, ...args: string[]): void {
  execFileSync("git", args, { cwd, stdio: "ignore" });
}

describe("changedFilesForRepo", () => {
  it("returns repo-relative paths for a subdirectory, including untracked files", async () => {
    const root = await tempDir();
    const pkg = join(root, "packages", "app");
    await mkdir(join(pkg, "src"), { recursive: true });
    await writeFile(join(pkg, "src", "util.ts"), "export const a = 1;\n");
    await writeFile(join(root, "outside.ts"), "export const b = 1;\n");
    git(root, "init", "-q");
    git(root, "-c", "user.email=t@t", "-c", "user.name=t", "add", ".");
    git(root, "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "init");

    await writeFile(join(pkg, "src", "util.ts"), "export const a = 2;\n");
    await writeFile(join(pkg, "src", "new.test.ts"), "export {};\n");
    await writeFile(join(root, "outside.ts"), "export const b = 2;\n");

    expect((await changedFilesForRepo(root, pkg, "HEAD")).sort()).toEqual([
      "src/new.test.ts",
      "src/util.ts",
    ]);
    expect((await changedFilesForRepo(pkg, pkg, "HEAD")).sort()).toEqual([
      "src/new.test.ts",
      "src/util.ts",
    ]);
  });
});

describe("readTsconfigAliases", () => {
  it("reads paths from a tsconfig with comments and trailing commas", async () => {
    const root = await tempDir();
    await writeFile(
      join(root, "tsconfig.json"),
      `{
  // generated by a framework template
  "compilerOptions": {
    "baseUrl": ".",
    "paths": { "@/*": ["src/*"], },
  },
}
`,
    );
    expect(await readTsconfigAliases(root)).toEqual({ "@/*": ["src/*"] });
  });
});
